name: AsyncKeepAlive
main: com.ishland.bukkit.AsyncKeepAlive.main.Launcher
version: 0.2.1-SNAPSHOT
author: ishland
description: AsyncKeepAlive is a plugin that keep the players' connections alive
depend: [ProtocolLib]
softdepend: [PlaceholderAPI]
