name: AsyncKeepAlive
main: com.ishland.bukkit.AsyncKeepAlive.main.AsyncKeepAlive
version: 0.0.1-SNAPSHOT
author: ishland
description: AsyncKeepAlive is a plugin that keep the players' connections alive
depend: [ProtocolLib]