name: AsyncKeepAlive
main: com.ishland.bukkit.AsyncKeepAlive.main.Launcher
version: 0.4-SNAPSHOT
author: ishland
description: AsyncKeepAlive is a plugin that keep the players' connections alive
depend: [ProtocolLib]
softdepend: [PlaceholderAPI]
commands:
  asynckeepalive:
    description: "The main command of AsyncKeepAlive"
    usage: "[Error] Something went wrong"
    aliases: [ak]
